"""empty message

Revision ID: 239163be713
Revises: 2b767cb617f
Create Date: 2017-03-12 01:49:36.039124

"""

# revision identifiers, used by Alembic.
revision = '239163be713'
down_revision = '2b767cb617f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('premium', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('premium_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('short_ad', sa.String(length=140), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'short_ad')
    op.drop_column('users', 'premium_expires')
    op.drop_column('users', 'premium')
    ### end Alembic commands ###
