"""empty message

Revision ID: 26e69577923
Revises: cd1d14e435
Create Date: 2017-03-08 18:18:30.706551

"""

# revision identifiers, used by Alembic.
revision = '26e69577923'
down_revision = 'cd1d14e435'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
