"""empty message

Revision ID: 4f4637caa22
Revises: 239163be713
Create Date: 2017-03-16 19:43:48.196561

"""

# revision identifiers, used by Alembic.
revision = '4f4637caa22'
down_revision = '239163be713'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_me_html')
    ### end Alembic commands ###
